_wandb:
    value:
        cli_version: 0.25.0
        code_path: code/run.py
        e:
            zj8fbcxvaw83xjufpffj881cg8sxhaey:
                args:
                    - distilbert-base-uncased
                    - mnli
                    - "1"
                    - "False"
                    - aft
                    - "5000"
                    - --pretrained_models=google/flan-t5-base
                    - --init_model=distilbert-base-uncased
                    - --prec=10
                    - --batch_size=32
                    - --lr=2e-5
                    - --no_augment=True
                    - --use_wandb=True
                codePath: run.py
                codePathLocal: run.py
                cpu_count: 40
                cpu_count_logical: 40
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "2161232625664"
                        used: "1874819129344"
                email: al_zhamankhan@kbtu.kz
                executable: /home/al_zhamankhan/.conda/envs/aft_clean/bin/python
                git:
                    commit: f07a9e25366a33d19190c86633d7ea20a6b8bcd9
                    remote: https://github.com/menghor-thuo/adaptive-feature-transfer
                gpu: NVIDIA A100-PCIE-40GB
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "42949672960"
                      name: NVIDIA A100-PCIE-40GB
                      uuid: GPU-14df5160-adca-f367-521b-7ba7a41f5837
                host: vm-tesla
                memory:
                    total: "265948102656"
                os: Linux-6.5.0-1017-gcp-x86_64-with-glibc2.35
                program: /home/al_zhamankhan/text_mining/adaptive-feature-transfer/run.py
                python: CPython 3.10.19
                root: /home/al_zhamankhan/text_mining/adaptive-feature-transfer
                startedAt: "2026-02-18T23:26:46.270384Z"
                writerId: zj8fbcxvaw83xjufpffj881cg8sxhaey
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 63
                - 71
            "3":
                - 2
                - 16
            "4": 3.10.19
            "5": 0.25.0
            "6": 5.2.0
            "12": 0.25.0
            "13": linux-x86_64
batch_size:
    value: 32
cache:
    value: false
ckpt_dir:
    value: null
dataset:
    value: mnli
eval_steps:
    value: 1000
init_model:
    value: distilbert-base-uncased
learn_scales:
    value: false
lr:
    value: 2e-05
method:
    value: aft
model_class:
    value: distilbert-base-uncased
no_augment:
    value: true
optimizer:
    value: sgd
prec:
    value: 10
pretrained_models:
    value: google/flan-t5-base
prior_freq:
    value: 1
prior_lr:
    value: 0.01
prior_pretrain_steps:
    value: 0
run_name:
    value: null
seed:
    value: 0
steps:
    value: 20000
train_frac:
    value: 1
use_val:
    value: false
use_wandb:
    value: true
wd:
    value: 0
